[package]
name = "monad-secp256k1-full-proto"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
bytes = "1"
h2 = "0.4"
http = "1"
monad-noise-secp256k1-proto = { path = "../monad-noise-secp256k1-proto" }
monad-quic = { path = "../monad-quic" }
monad-quic-npub-proto = { path = "../monad-quic-npub-proto" }
monad-secp256k1-identity = { path = "../monad-secp256k1-identity" }
quinn = "0.11"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "io-util", "time"] }
tracing = "0.1"
