[package]
name = "monad-client"
version = "0.1.0"
edition = "2021"

[dependencies]
monad-common = { path = "../monad-common" }
monad-quic = { path = "../monad-quic" }
quinn = "0.11"
h2 = "0.4"
tokio = { version = "1", features = ["full"] }
bytes = "1"
clap = { version = "4", features = ["derive"] }
hex = "0.4"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
http = "1"
anyhow = "1"
serde_json = "1"
rand = "0.9"
rusqlite = "0.31"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
async-trait = "0.1"
cashu = { git = "https://github.com/cashubtc/cdk.git", tag = "v0.17.6", package = "cashu", default-features = false }
cdk-spilman = { git = "https://github.com/SatsAndSports/cashu_spilman_channels.git", rev = "10bf2d4d5994a94574102d3c144d06e481dbf97e", package = "cdk-spilman", features = ["wallet", "configurable-host-reqwest", "client-sqlite"] }

[dev-dependencies]
tempfile = "3"
cdk-spilman-test-mint = { git = "https://github.com/SatsAndSports/cashu_spilman_channels.git", rev = "10bf2d4d5994a94574102d3c144d06e481dbf97e", package = "cdk-spilman-test-mint", default-features = false, features = ["http"] }
